version: '3.7'
services:
  compute01:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: master
    volumes:
      - ./hadoop-3.2.2:/opt/hadoop
    stdin_open: true
    tty: true
    networks:
      hadoop:
        ipv4_address: 10.40.0.2

networks:
  hadoop:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.40.0.0/24
